In [6]:
# --- Setup path so Jupyter can find src/ ---
import sys, os
sys.path.append(os.path.abspath(".."))  # project root

import pandas as pd
from src.features import simple_feature_engineering
from src.data_utils import save_processed

# Load raw dataset
df = pd.read_csv("../data/raw/restaurant_ratings.csv")

# Apply feature engineering
df = simple_feature_engineering(df)

# Drop irrelevant columns
drop_cols = [
    'Restaurant ID',
    'Restaurant Name',
    'Address',
    'Locality Verbose',
    'Rating color',
    'Rating text'
]
df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

# âœ… Save processed data (use default path inside data_utils)
save_processed(df)

# Preview processed data
df.head()

Saved processed data to data\processed\restaurant_ratings_clean.csv

,Country Code,City,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes,PrimaryCuisine
0,162,Makati City,"Century City Mall, Poblacion, Makati City",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,No,3,4.8,314,French
1,162,Makati City,"Little Tokyo, Legaspi Village, Makati City",121.014101,14.553708,Japanese,1200,Botswana Pula(P),1,0,0,No,3,4.5,591,Japanese
2,162,Mandaluyong City,"Edsa Shangri-La, Ortigas, Mandaluyong City",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,No,4,4.4,270,Seafood
3,162,Mandaluyong City,"SM Megamall, Ortigas, Mandaluyong City",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,No,4,4.9,365,Japanese
4,162,Mandaluyong City,"SM Megamall, Ortigas, Mandaluyong City",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,No,4,4.8,229,Japanese